export const BioPlaceholders = [
    "#adventureaddict 🌍 | #foodie 🍕 | Making memories ✨",
    "#writer_in_motion 🖋️ | #coffeelover ☕ | Seeking inspiration daily",
    "Passionate about #fitness 💪 | #veganLife 🥗 | Live. Love. Laugh",
    "#travelbug 🌍 | Capturing moments 📸 | #Wanderlust",
    "#fashionista | Living my #DreamLife 💫 | NY-LA",
    "#techgeek 🖥️ | #gamer 🎮 | Exploring the virtual world",
    "#art_enthusiast 🎨 | Expressing in colors | #dreamer",
    "#fitnessfreak 💪 | #healthyliving 🥗 | Life is a workout",
    "#musiclover 🎵 | Grooving to the rhythm of life | #DJ",
    "Living #sustainably 🌿 | #ecowarrior | Earth is home",
    "Chasing #sunsets 🌅 | #nature_lover 🌲 | Life's an adventure",
    "In love with #books 📚 | #storyteller | Living through words",
    "#yoga 🧘‍♀️ | Finding peace within | #mindfulness",
    "#baking 🍰 | Sweetening life one bite at a time | #food_blogger",
    "#photography 📸 | Capturing Life's little moments | #worldtraveler",
    "#doglover 🐶 | #pet_mom | Life is better with furry friends",
    "#plantparent 🌿 | Growing love | #greenthumb",
    "Passionate #chef 👨‍🍳 | Exploring flavors | #gourmet_life",
    "#cocktail_connoisseur 🍸 | Mixing life's pleasures | #mixologist",
    "#thrillseeker 🎢 | #adventurer | Living life on the edge",
    "NYC Dreamer 🗽 | 12.01.01",
    "Tokyo 🌸 | 26yo | #foodie 🍣",
    "Warsaw 🇵🇱 | 23yo | #traveler 🌍",
    "London 🇬🇧 | 25yo | #fashionista 👠",
    "Paris 🇫🇷 | 05.05.98 | #foodie 🍷",
    "LA 🇺🇸 | 28yo | #traveler 🌴",
    "NYC 🇺🇸 | 29yo | #foodie 🍕",
    "LA 🇺🇸 | 23.03.02 | #fashionista 👠",
    "London 🇬🇧 | 31yo | #traveler 🌍",
]

export const GirlDescPlaceholders = [
    "Confidence is the best outfit a girl can wear 💖",
    "embracing the sunshine and the joy within ☀️",
    "Living life in full bloom 🌸",
    "Bold and beautiful, in every way possible 💪",
    "chasing dreams in heels 👠",
    "In a world full of trends, I want to remain a classic 🕶️",
    "She's a storm not the kind you run from, the kind you chase 🌪️",
    "creating my own fairytale, one day at a time 🏰",
    "Just a small-town girl with big city dreams",
    "Embracing the mess and the magic within ✨",
    "A combination of sensitive and savage...",
    "A splash of color in a black and white world 🌈",
    "A poem, full of rhyme and rhythm 💖💖💖",
    "Rising and shining, making each day count 🌞",
    "finding beauty in the ordinary, making it extraordinary",
    "In the heart of the city, finding my own rhythm 🎵",
    "A day in the life of a sunflower, reaching for the light 🌻",
    "Confidence is my superpower #girlpower #confidence",
    "chasing sunsets and dreams #dreamer #sunsetLover",
    "Blossoming into a fearless soul 🌸🌸🌸 #braveheart #growth_mindset",
    "Slaying in my own way 👠 #fashionista #own_your_style",
    "life is a beautiful ride, enjoy every moment #life_is_beautiful #joyfuljourney",
    "Lost in the right direction 🗺️ #wanderlust #travel_diaries",
    "embracing the magic within and around ✨ #believe_in_magic #sparkle_and_shine",
    '"She is both, a masterpiece and a work in progress" 💖 #selflove #workinprogress',
    "Made of stardust, dreams, and endless possibilities... 🌌 #dreambig #limitless",
    "In love with every moment of this journey called life 🌍 #lifelover #cherish_every_moment",
    "no filter"
]

export const ManDescPlaceholders = [
    "Mastering the art of the journey, not the destination #life_explorer #adventure",
    "In tune with the rhythm of the city #citylife #urban_explorer",
    "chasing horizons and expanding boundaries #dreamchaser #limitless",
    "In the concrete jungle, creating my own path #urban_jungle #pathfinder",
    "Turning moments into memories, one click at a time #photographer #making_memories",
    "Mastering the art of the hustle 💪👊",
    "Living life in the fast lane 🚗💨",
    "Pushing limits, breaking boundaries 🌍🚀",
    "Fuelled by coffee, driven by ambition ☕💼",
    "On top of the world, where eagles dare 🦅🏔️",
    "Life's a game, play it hard 🎲🏆",
    "In the wilderness, finding my strength 🌲🐾",
    "living on the edge, where the view is best.",
    "In the face of risk, finding reward.",
    "unleashed \n untamed \n undefeated",
    "daring greatly \n living boldly.",
    "Embracing the dirt, the sweat, the victory.",
    "Life's a fight, and I'm in the ring 👊",
    "Treading paths less traveled, finding unseen vistas.",
    "calm in the chaos, strong in the struggle 💪",
    "Burning rubber, living life at full speed."
]

export const GirlCommentPlaceholders = [
    "Absolutely stunning! 💖",
    "Glowing with beauty and grace!",
    "Elegance personified! 👌",
    "Captivating! You shine bright. 🌟",
    "Your smile is contagious! 😊",
    "Effortlessly chic! 🙌",
    "Radiating positivity! ✨",
    "Your style is impeccable!",
    "such a vibrant spirit",
    "Mesmerizing, as always! 👏",
    "Simply enchanting! 🌟",
    "You're glowing! 💫",
    "Dazzling beauty!",
    "Your energy is inspiring! 💪",
    "Incredible! Beauty inside out.",
    "Love your unique style! 👌",
    "Beauty in every frame! 📸",
    "A breath of fresh air! 💐",
    "Your smile lights up the room! 😊",
    "Dazzling! The camera loves you",
    "absolutely radiant ",
    "Exquisite elegance! 👌💖",
    "beautiful inside and out 🌹🌹🌹",
    "Spreading sunshine with your smile! ☀️",
    "Aesthetics on point! 👌",
    "Your energy is magnetic!",
    "Heart-stoppingly beautiful! 💓",
    "gorgeous in every sense",
]

export const ManCommentPlaceholders = [
    "Looking sharp, mate! 👌",
    "Style on point! 🎯",
    "Powerful vibes! 💪",
    "Epic shot, bro!",
    "Cool and composed. 😎",
    "unstoppable energy",
    "Classy and charismatic!",
    "Impressive and inspiring! 👏",
    "Absolute legend! 🏆",
    "Smooth operator! 😎",
    "Strength and spirit! 💪",
    "king of cool",
    "Bold and brave!",
    "Looking like a boss!",
    "acing the game!",
    "Radiating positivity! 😄",
    "Trailblazer!",
    "Rocking that look! 👌👌 💪",
    "You're on fire! 🔥",
    "champion mindset!",
    "The epitome of cool! 😎",
    "Adventure in your eyes!",
    "Keep up the great work! 👍",
    "timeless style, mate",
    "that look is a knockout 😄😄",
    "A class apart!",
    "Breaking barriers! 💪",
    "turning heads with that style!"
]